apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: macula

resources:
  - ../../../base/apps/console
  - configmap.yaml
  - secret.yaml
  - pvc.yaml

patches:
  - target:
      kind: Deployment
      name: macula-console
    path: deployment-patch.yaml
