apiVersion: v1
kind: Service
metadata:
  name: macula-console
  namespace: macula
spec:
  type: LoadBalancer
  selector:
    app: macula-console
  ports:
  - name: http
    port: 80
    targetPort: 4000
